label start:
    call scene_maison_1
    call scene_ville_1
    call scene_parlement_1
    call scene_apres_vote_1
    call scene_maison_2
    call scene_maison_2_2
    call scene_maison_3
    call scene_ville_2
    call scene_parlement_2
    call scene_apres_vote_2
    call scene_maison_4
    call scene_maison_5
    call scene_ville_3
    call scene_parlement_3
    call scene_apres_vote_3
    call scene_maison_5_2
    call scene_maison_5_3
    call scene_maison_6
    call scene_ville_4
    call scene_parlement_4
    call scene_apres_vote_4
    call scene_maison_6_2
    call scene_maison_7
    call scene_ville_5
    call scene_parlement_5
    call scene_fin
    
    return